pkt-cash/pktd

contrib/deb/build.sh
contrib/docker/Dockerfile
contrib/docker/build-notworking.sh
contrib/docker/build.sh
contrib/freebsd/build.sh
contrib/gem/build.sh
contrib/macos/build.sh
contrib/rpm/build.sh

Add build scripts for RPM, DEB, MacOSX DMG, FreeBSD txz, Ruby gem, and Docker

adding build scripts for Mac OS X, deb, rpm, freebsd, gem, and Docker

---

connmgr/dynamicbanscore.go
connmgr/dynamicbanscore_test.go

Import of fix for #1510 mainline [DynamicBanScore String() deadlock]

---

go.mod
go.sum

Should close out [#18](https://github.com/pkt-cash/pktd/issues/18) [develop branch]

[develop] Fix CVE-2019-11840

---

blockchain/scriptval_test.go
blockchain/testdata/util.go
btcd.go
database/ffldb/driver_test.go
pktwallet/btcwallet.go

do some side-by-side test with just this + 
https://github.com/pkt-cash/pktd/pull/70﻿ just FYI amazed w 1.14+

Increse GOMAXPROCS > See https://github.com/pkt-cash/pktd/pull/70#issue-507143914 for full rationale)

---

pktwallet/wallet/wallet.go

Replacement for PR#66, fixing the typo'd inclusion of #65
﻿Adding additional mutex for locked outpoints,
adapted from roasbeef and massaged from PR#715 mainline

wallet: add addl mutex for locked outpoints 

---

netsync/manager.go

* remove redundant sending to msg.reply
in processBlockMsg in blockHandler

backport c617c3536ad4312e15d150865c3af2bed6ef14b6

---

chaincfg/globalcfg/config.go

@johnsonjh what is your opinion of this ?

RFC soft fork - Reject blocks with PacketCrypt version 1

---

btcutil/base58/base58check_test.go

Fix for base58check_test logic

---

server.go

* Backporting of mainline btcsuite#1477 and
* adaptation of gcash#320 peer connection logic.

Port upstream #1477 + gcash #320 peer handling logic

---

pktwallet/waddrmgr/manager_test.go

Better reliability; disable parallel waddrmgr tests﻿

Better reliability; disable parallel waddrmgr tests

---

pktwallet/config.go

pktwallet: Remove code duplication in loadConfig.

---

wire/common_test.go

* Fixes https://github.com/pkt-cash/pktd/issues/112

Remove broken TestRandomUint64 test

---

service_windows.go

* Change display name of Windows Service from BTCD -> PKTD

Change display name of Windows Service: BTC->PKT

---

addrmgr/addrmanager.go
connmgr/seed.go
peer/mrunoncemap.go
peer/peer.go
pktwallet/log.go
pktwallet/wallet/createtx.go
pktwallet/walletsetup.go
rpcserver.go
rpcwebsocket.go
server.go
txscript/script.go
txscript/sign.go

Use of panic() as these *should* be usually impossible situations (but previously weren't checked.)

Add some additional error checking

---

log.go
pktwallet/docs/force_rescans.md
pktwallet/log.go
rpcserverhelp.go

﻿
* BTCN -> PKTN
* BTCD -> PKTD
* BTCW -> PKTW
* BCDB -> PKDB
* Update RPC help and docs

Rename logging subsystem channels

---

README.md

* Because the original is horrible.﻿

Spelling and grammar fixes for the README markdown

---

mempool/mempool.go

﻿* Found via race detector + regression testing

Fix deadlock in mempool

---

btcec/precompute.go

﻿* Compare string type to an empty/null string.

Small optimization: Avoid unnecessary conversion.

---

rpcserver.go

See https://github.com/btcsuite/btcd/pull/1614/commits/9f59ed6e7013bb4f5685809f4c99109ff8cfe965

Fix monetary unit: backport mainline #1614

---

config.go
go.mod
go.sum
pktd.go
pktwallet/config.go
pktwallet/pktwallet.go

* Also, fix the help message for the pprof server
to correctly list the port range as 1024-65535.

Add support for the StatsViz runtime visualization server.

---

neutrino/headerfs/index.go

checking for genesis block

---

pktlog/log/log.go

This patch disables colorization of individual fields in the log output when colored output is disabled and also adds an extra log flag to disable output of the log timestamp.
The colored output currently does not work on Windows and the unprocessed escape sequences make the output largely unreadable. This change allows Windows users (including the Pkt.world wallet) to disable the colors in the output.
Disabling timestamping of log entries can be useful when the log view is small (like the old fixed width Windows console) or when timestamps are added by external logging utilities (like systemd/journald).

Fixed unwanted colorization in log output

---

.github/workflows/go.yml
README.md

. "go.yml" file added with an action to build & test the code on pushes and PR merges;
.  build status indicator added to README.md;

GitHub action added to automate the build

---

.github/workflows/go.yml

Fix the shell used to run build and test actions

Github Action to automate build and tests

---

lnd/cmd/lncli/cmd_profile.go
lnd/cmd/lncli/main.go
lnd/cmd/lncli/profile.go
test/lnd_test.sh
test/unlockWallet.pl

. macaroons options removed from pldctl profile files;
. added a test to unlock wallet command;

Scrap macaroon options from pldctl profile

---

lnd/lnd.go
lnd/lnrpc/gen_protos.sh
lnd/lnrpc/restrpc/restrpc.go
lnd/lnrpc/rpc.pb.gw.go

- added commands needed for mobile apps
- restored rpc.pb.gw.go and gen protos to original

Removinggrpc

---

lnd/lnrpc/restrpc/restrpc.go
test/REST_test.sh

The following were added/changed/fixed:
. implementation of command **getrecoveryinfo** REST endpoint;
. implementation of command **debuglevel** REST endpoint;
. implementation of command **stop** REST endpoint;

Implementation of some pld REST endpoins

---

lnd/lnrpc/restrpc/restrpc.go
test/REST_test.sh

The following were added/changed/fixed:
. implementation of all commands from Channel Management as REST endpoints;

Implementation channels REST endpoins

---

lnd/lnrpc/restrpc/restrpc.go
test/REST_test.sh

The following were added/changed/fixed:
. elimination of all URI parameters from REST endpoins;
. revision and grouping of all URI REST endpoins;

Revision of all URI endpoints
